#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="correos")]
public partial class DbCorreosDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCorreos(Correos instance);
  partial void UpdateCorreos(Correos instance);
  partial void DeleteCorreos(Correos instance);
  #endregion
	
	public DbCorreosDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["correosConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DbCorreosDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DbCorreosDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DbCorreosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DbCorreosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Correos> Correos
	{
		get
		{
			return this.GetTable<Correos>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.o365_activacion")]
public partial class Correos : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _cuenta;
	
	private System.Nullable<int> _matricula;
	
	private string _passw;
	
	private System.Nullable<int> _folio;
	
	private System.Nullable<int> _situacion;
	
	private System.Nullable<System.DateTime> _fh_pw_presetear;
	
	private System.Nullable<System.DateTime> _fh_pw_generado;
	
	private System.Nullable<System.DateTime> _fh_acceso_a_activ;
	
	private string _quien_reseteo;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncuentaChanging(string value);
    partial void OncuentaChanged();
    partial void OnmatriculaChanging(System.Nullable<int> value);
    partial void OnmatriculaChanged();
    partial void OnpasswChanging(string value);
    partial void OnpasswChanged();
    partial void OnfolioChanging(System.Nullable<int> value);
    partial void OnfolioChanged();
    partial void OnsituacionChanging(System.Nullable<int> value);
    partial void OnsituacionChanged();
    partial void Onfh_pw_presetearChanging(System.Nullable<System.DateTime> value);
    partial void Onfh_pw_presetearChanged();
    partial void Onfh_pw_generadoChanging(System.Nullable<System.DateTime> value);
    partial void Onfh_pw_generadoChanged();
    partial void Onfh_acceso_a_activChanging(System.Nullable<System.DateTime> value);
    partial void Onfh_acceso_a_activChanged();
    partial void Onquien_reseteoChanging(string value);
    partial void Onquien_reseteoChanged();
    #endregion
	
	public Correos()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuenta", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string cuenta
	{
		get
		{
			return this._cuenta;
		}
		set
		{
			if ((this._cuenta != value))
			{
				this.OncuentaChanging(value);
				this.SendPropertyChanging();
				this._cuenta = value;
				this.SendPropertyChanged("cuenta");
				this.OncuentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="Int")]
	public System.Nullable<int> matricula
	{
		get
		{
			return this._matricula;
		}
		set
		{
			if ((this._matricula != value))
			{
				this.OnmatriculaChanging(value);
				this.SendPropertyChanging();
				this._matricula = value;
				this.SendPropertyChanged("matricula");
				this.OnmatriculaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passw", DbType="VarChar(15)")]
	public string passw
	{
		get
		{
			return this._passw;
		}
		set
		{
			if ((this._passw != value))
			{
				this.OnpasswChanging(value);
				this.SendPropertyChanging();
				this._passw = value;
				this.SendPropertyChanged("passw");
				this.OnpasswChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio", DbType="Int")]
	public System.Nullable<int> folio
	{
		get
		{
			return this._folio;
		}
		set
		{
			if ((this._folio != value))
			{
				this.OnfolioChanging(value);
				this.SendPropertyChanging();
				this._folio = value;
				this.SendPropertyChanged("folio");
				this.OnfolioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacion", DbType="Int")]
	public System.Nullable<int> situacion
	{
		get
		{
			return this._situacion;
		}
		set
		{
			if ((this._situacion != value))
			{
				this.OnsituacionChanging(value);
				this.SendPropertyChanging();
				this._situacion = value;
				this.SendPropertyChanged("situacion");
				this.OnsituacionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fh_pw_presetear", DbType="DateTime")]
	public System.Nullable<System.DateTime> fh_pw_presetear
	{
		get
		{
			return this._fh_pw_presetear;
		}
		set
		{
			if ((this._fh_pw_presetear != value))
			{
				this.Onfh_pw_presetearChanging(value);
				this.SendPropertyChanging();
				this._fh_pw_presetear = value;
				this.SendPropertyChanged("fh_pw_presetear");
				this.Onfh_pw_presetearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fh_pw_generado", DbType="DateTime")]
	public System.Nullable<System.DateTime> fh_pw_generado
	{
		get
		{
			return this._fh_pw_generado;
		}
		set
		{
			if ((this._fh_pw_generado != value))
			{
				this.Onfh_pw_generadoChanging(value);
				this.SendPropertyChanging();
				this._fh_pw_generado = value;
				this.SendPropertyChanged("fh_pw_generado");
				this.Onfh_pw_generadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fh_acceso_a_activ", DbType="DateTime")]
	public System.Nullable<System.DateTime> fh_acceso_a_activ
	{
		get
		{
			return this._fh_acceso_a_activ;
		}
		set
		{
			if ((this._fh_acceso_a_activ != value))
			{
				this.Onfh_acceso_a_activChanging(value);
				this.SendPropertyChanging();
				this._fh_acceso_a_activ = value;
				this.SendPropertyChanged("fh_acceso_a_activ");
				this.Onfh_acceso_a_activChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quien_reseteo", DbType="VarChar(50)")]
	public string quien_reseteo
	{
		get
		{
			return this._quien_reseteo;
		}
		set
		{
			if ((this._quien_reseteo != value))
			{
				this.Onquien_reseteoChanging(value);
				this.SendPropertyChanging();
				this._quien_reseteo = value;
				this.SendPropertyChanged("quien_reseteo");
				this.Onquien_reseteoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
