#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ingresos_v3")]
public partial class DBIngresosDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertPago(Pago instance);
  partial void UpdatePago(Pago instance);
  partial void DeletePago(Pago instance);
  partial void InsertDetalleDePago(DetalleDePago instance);
  partial void UpdateDetalleDePago(DetalleDePago instance);
  partial void DeleteDetalleDePago(DetalleDePago instance);
  #endregion
	
	public DBIngresosDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Ingresos_v3ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBIngresosDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBIngresosDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBIngresosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBIngresosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Pago> Pagos
	{
		get
		{
			return this.GetTable<Pago>();
		}
	}
	
	public System.Data.Linq.Table<DetalleDePago> DetalleDePagos
	{
		get
		{
			return this.GetTable<DetalleDePago>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEXEGetFolio")]
	public int spEXEGetFolio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zona", DbType="TinyInt")] System.Nullable<byte> zona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Plantel", DbType="TinyInt")] System.Nullable<byte> plantel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Folio", DbType="Int")] ref System.Nullable<int> folio)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), zona, plantel, folio);
		folio = ((System.Nullable<int>)(result.GetParameterValue(2)));
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pagos")]
public partial class Pago : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _PagoID;
	
	private byte _PlantelID;
	
	private int _AlumnoID;
	
	private int _Folio;
	
	private string _Referencia;
	
	private decimal _Total;
	
	private string _Ciclo;
	
	private byte _Estatus;
	
	private System.DateTime _FechaDeAlta;
	
	private System.Nullable<System.DateTime> _FechaDePago;
	
	private System.Nullable<byte> _TipoDePago;
	
	private string _Comentarios;
	
	private System.Nullable<int> _Tipo;
	
	private EntitySet<DetalleDePago> _DetalleDePagos;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPagoIDChanging(int value);
    partial void OnPagoIDChanged();
    partial void OnPlantelIDChanging(byte value);
    partial void OnPlantelIDChanged();
    partial void OnAlumnoIDChanging(int value);
    partial void OnAlumnoIDChanged();
    partial void OnFolioChanging(int value);
    partial void OnFolioChanged();
    partial void OnReferenciaChanging(string value);
    partial void OnReferenciaChanged();
    partial void OnTotalChanging(decimal value);
    partial void OnTotalChanged();
    partial void OnCicloChanging(string value);
    partial void OnCicloChanged();
    partial void OnEstatusChanging(byte value);
    partial void OnEstatusChanged();
    partial void OnFechaDeAltaChanging(System.DateTime value);
    partial void OnFechaDeAltaChanged();
    partial void OnFechaDePagoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaDePagoChanged();
    partial void OnTipoDePagoChanging(System.Nullable<byte> value);
    partial void OnTipoDePagoChanged();
    partial void OnComentariosChanging(string value);
    partial void OnComentariosChanged();
    partial void OnTipoChanging(System.Nullable<int> value);
    partial void OnTipoChanged();
    #endregion
	
	public Pago()
	{
		this._DetalleDePagos = new EntitySet<DetalleDePago>(new Action<DetalleDePago>(this.attach_DetalleDePagos), new Action<DetalleDePago>(this.detach_DetalleDePagos));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int PagoID
	{
		get
		{
			return this._PagoID;
		}
		set
		{
			if ((this._PagoID != value))
			{
				this.OnPagoIDChanging(value);
				this.SendPropertyChanging();
				this._PagoID = value;
				this.SendPropertyChanged("PagoID");
				this.OnPagoIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlantelID", DbType="TinyInt NOT NULL")]
	public byte PlantelID
	{
		get
		{
			return this._PlantelID;
		}
		set
		{
			if ((this._PlantelID != value))
			{
				this.OnPlantelIDChanging(value);
				this.SendPropertyChanging();
				this._PlantelID = value;
				this.SendPropertyChanged("PlantelID");
				this.OnPlantelIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", DbType="Int NOT NULL")]
	public int AlumnoID
	{
		get
		{
			return this._AlumnoID;
		}
		set
		{
			if ((this._AlumnoID != value))
			{
				this.OnAlumnoIDChanging(value);
				this.SendPropertyChanging();
				this._AlumnoID = value;
				this.SendPropertyChanged("AlumnoID");
				this.OnAlumnoIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folio", DbType="Int NOT NULL")]
	public int Folio
	{
		get
		{
			return this._Folio;
		}
		set
		{
			if ((this._Folio != value))
			{
				this.OnFolioChanging(value);
				this.SendPropertyChanging();
				this._Folio = value;
				this.SendPropertyChanged("Folio");
				this.OnFolioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="Char(21) NOT NULL", CanBeNull=false)]
	public string Referencia
	{
		get
		{
			return this._Referencia;
		}
		set
		{
			if ((this._Referencia != value))
			{
				this.OnReferenciaChanging(value);
				this.SendPropertyChanging();
				this._Referencia = value;
				this.SendPropertyChanged("Referencia");
				this.OnReferenciaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="SmallMoney NOT NULL")]
	public decimal Total
	{
		get
		{
			return this._Total;
		}
		set
		{
			if ((this._Total != value))
			{
				this.OnTotalChanging(value);
				this.SendPropertyChanging();
				this._Total = value;
				this.SendPropertyChanged("Total");
				this.OnTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciclo", DbType="Char(5) NOT NULL", CanBeNull=false)]
	public string Ciclo
	{
		get
		{
			return this._Ciclo;
		}
		set
		{
			if ((this._Ciclo != value))
			{
				this.OnCicloChanging(value);
				this.SendPropertyChanging();
				this._Ciclo = value;
				this.SendPropertyChanged("Ciclo");
				this.OnCicloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="TinyInt NOT NULL")]
	public byte Estatus
	{
		get
		{
			return this._Estatus;
		}
		set
		{
			if ((this._Estatus != value))
			{
				this.OnEstatusChanging(value);
				this.SendPropertyChanging();
				this._Estatus = value;
				this.SendPropertyChanged("Estatus");
				this.OnEstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeAlta", DbType="DateTime NOT NULL")]
	public System.DateTime FechaDeAlta
	{
		get
		{
			return this._FechaDeAlta;
		}
		set
		{
			if ((this._FechaDeAlta != value))
			{
				this.OnFechaDeAltaChanging(value);
				this.SendPropertyChanging();
				this._FechaDeAlta = value;
				this.SendPropertyChanged("FechaDeAlta");
				this.OnFechaDeAltaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDePago", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> FechaDePago
	{
		get
		{
			return this._FechaDePago;
		}
		set
		{
			if ((this._FechaDePago != value))
			{
				this.OnFechaDePagoChanging(value);
				this.SendPropertyChanging();
				this._FechaDePago = value;
				this.SendPropertyChanged("FechaDePago");
				this.OnFechaDePagoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePago", DbType="TinyInt")]
	public System.Nullable<byte> TipoDePago
	{
		get
		{
			return this._TipoDePago;
		}
		set
		{
			if ((this._TipoDePago != value))
			{
				this.OnTipoDePagoChanging(value);
				this.SendPropertyChanging();
				this._TipoDePago = value;
				this.SendPropertyChanged("TipoDePago");
				this.OnTipoDePagoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentarios", DbType="VarChar(50)")]
	public string Comentarios
	{
		get
		{
			return this._Comentarios;
		}
		set
		{
			if ((this._Comentarios != value))
			{
				this.OnComentariosChanging(value);
				this.SendPropertyChanging();
				this._Comentarios = value;
				this.SendPropertyChanged("Comentarios");
				this.OnComentariosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Int")]
	public System.Nullable<int> Tipo
	{
		get
		{
			return this._Tipo;
		}
		set
		{
			if ((this._Tipo != value))
			{
				this.OnTipoChanging(value);
				this.SendPropertyChanging();
				this._Tipo = value;
				this.SendPropertyChanged("Tipo");
				this.OnTipoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pago_DetalleDePago", Storage="_DetalleDePagos", ThisKey="PagoID", OtherKey="PagoID")]
	public EntitySet<DetalleDePago> DetalleDePagos
	{
		get
		{
			return this._DetalleDePagos;
		}
		set
		{
			this._DetalleDePagos.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DetalleDePagos(DetalleDePago entity)
	{
		this.SendPropertyChanging();
		entity.Pago = this;
	}
	
	private void detach_DetalleDePagos(DetalleDePago entity)
	{
		this.SendPropertyChanging();
		entity.Pago = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetalleDePagos")]
public partial class DetalleDePago : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _DetalleID;
	
	private int _PagoID;
	
	private string _Clave;
	
	private string _Concepto;
	
	private decimal _Monto;
	
	private EntityRef<Pago> _Pago;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetalleIDChanging(int value);
    partial void OnDetalleIDChanged();
    partial void OnPagoIDChanging(int value);
    partial void OnPagoIDChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnConceptoChanging(string value);
    partial void OnConceptoChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    #endregion
	
	public DetalleDePago()
	{
		this._Pago = default(EntityRef<Pago>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetalleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int DetalleID
	{
		get
		{
			return this._DetalleID;
		}
		set
		{
			if ((this._DetalleID != value))
			{
				this.OnDetalleIDChanging(value);
				this.SendPropertyChanging();
				this._DetalleID = value;
				this.SendPropertyChanged("DetalleID");
				this.OnDetalleIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagoID", DbType="Int NOT NULL")]
	public int PagoID
	{
		get
		{
			return this._PagoID;
		}
		set
		{
			if ((this._PagoID != value))
			{
				if (this._Pago.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnPagoIDChanging(value);
				this.SendPropertyChanging();
				this._PagoID = value;
				this.SendPropertyChanged("PagoID");
				this.OnPagoIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string Clave
	{
		get
		{
			return this._Clave;
		}
		set
		{
			if ((this._Clave != value))
			{
				this.OnClaveChanging(value);
				this.SendPropertyChanging();
				this._Clave = value;
				this.SendPropertyChanged("Clave");
				this.OnClaveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Concepto
	{
		get
		{
			return this._Concepto;
		}
		set
		{
			if ((this._Concepto != value))
			{
				this.OnConceptoChanging(value);
				this.SendPropertyChanging();
				this._Concepto = value;
				this.SendPropertyChanged("Concepto");
				this.OnConceptoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="SmallMoney NOT NULL")]
	public decimal Monto
	{
		get
		{
			return this._Monto;
		}
		set
		{
			if ((this._Monto != value))
			{
				this.OnMontoChanging(value);
				this.SendPropertyChanging();
				this._Monto = value;
				this.SendPropertyChanged("Monto");
				this.OnMontoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pago_DetalleDePago", Storage="_Pago", ThisKey="PagoID", OtherKey="PagoID", IsForeignKey=true)]
	public Pago Pago
	{
		get
		{
			return this._Pago.Entity;
		}
		set
		{
			Pago previousValue = this._Pago.Entity;
			if (((previousValue != value) 
						|| (this._Pago.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Pago.Entity = null;
					previousValue.DetalleDePagos.Remove(this);
				}
				this._Pago.Entity = value;
				if ((value != null))
				{
					value.DetalleDePagos.Add(this);
					this._PagoID = value.PagoID;
				}
				else
				{
					this._PagoID = default(int);
				}
				this.SendPropertyChanged("Pago");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
