//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EscolarModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EstaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EstaEntities object using the connection string found in the 'EstaEntities' section of the application configuration file.
        /// </summary>
        public EstaEntities() : base("name=EstaEntities", "EstaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EstaEntities object.
        /// </summary>
        public EstaEntities(string connectionString) : base(connectionString, "EstaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EstaEntities object.
        /// </summary>
        public EstaEntities(EntityConnection connection) : base(connection, "EstaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bitacora> Bitacoras
        {
            get
            {
                if ((_Bitacoras == null))
                {
                    _Bitacoras = base.CreateObjectSet<Bitacora>("Bitacoras");
                }
                return _Bitacoras;
            }
        }
        private ObjectSet<Bitacora> _Bitacoras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwRPTParcial1XALU> vwRPTParcial1XALU
        {
            get
            {
                if ((_vwRPTParcial1XALU == null))
                {
                    _vwRPTParcial1XALU = base.CreateObjectSet<vwRPTParcial1XALU>("vwRPTParcial1XALU");
                }
                return _vwRPTParcial1XALU;
            }
        }
        private ObjectSet<vwRPTParcial1XALU> _vwRPTParcial1XALU;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwRPTParcial1XGPO> vwRPTParcial1XGPO
        {
            get
            {
                if ((_vwRPTParcial1XGPO == null))
                {
                    _vwRPTParcial1XGPO = base.CreateObjectSet<vwRPTParcial1XGPO>("vwRPTParcial1XGPO");
                }
                return _vwRPTParcial1XGPO;
            }
        }
        private ObjectSet<vwRPTParcial1XGPO> _vwRPTParcial1XGPO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwPlantele> vwPlanteles
        {
            get
            {
                if ((_vwPlanteles == null))
                {
                    _vwPlanteles = base.CreateObjectSet<vwPlantele>("vwPlanteles");
                }
                return _vwPlanteles;
            }
        }
        private ObjectSet<vwPlantele> _vwPlanteles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bitacoras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBitacoras(Bitacora bitacora)
        {
            base.AddObject("Bitacoras", bitacora);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwRPTParcial1XALU EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwRPTParcial1XALU(vwRPTParcial1XALU vwRPTParcial1XALU)
        {
            base.AddObject("vwRPTParcial1XALU", vwRPTParcial1XALU);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwRPTParcial1XGPO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwRPTParcial1XGPO(vwRPTParcial1XGPO vwRPTParcial1XGPO)
        {
            base.AddObject("vwRPTParcial1XGPO", vwRPTParcial1XGPO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwPlanteles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwPlanteles(vwPlantele vwPlantele)
        {
            base.AddObject("vwPlanteles", vwPlantele);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EscolarModel", Name="Bitacora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bitacora : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bitacora object.
        /// </summary>
        /// <param name="z">Initial value of the Z property.</param>
        /// <param name="p">Initial value of the P property.</param>
        /// <param name="registros">Initial value of the Registros property.</param>
        /// <param name="ciclo">Initial value of the Ciclo property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        public static Bitacora CreateBitacora(global::System.Byte z, global::System.Byte p, global::System.Int32 registros, global::System.String ciclo, global::System.DateTime fecha)
        {
            Bitacora bitacora = new Bitacora();
            bitacora.Z = z;
            bitacora.P = p;
            bitacora.Registros = registros;
            bitacora.Ciclo = ciclo;
            bitacora.Fecha = fecha;
            return bitacora;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Z
        {
            get
            {
                return _Z;
            }
            set
            {
                if (_Z != value)
                {
                    OnZChanging(value);
                    ReportPropertyChanging("Z");
                    _Z = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Z");
                    OnZChanged();
                }
            }
        }
        private global::System.Byte _Z;
        partial void OnZChanging(global::System.Byte value);
        partial void OnZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte P
        {
            get
            {
                return _P;
            }
            set
            {
                if (_P != value)
                {
                    OnPChanging(value);
                    ReportPropertyChanging("P");
                    _P = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("P");
                    OnPChanged();
                }
            }
        }
        private global::System.Byte _P;
        partial void OnPChanging(global::System.Byte value);
        partial void OnPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Registros
        {
            get
            {
                return _Registros;
            }
            set
            {
                if (_Registros != value)
                {
                    OnRegistrosChanging(value);
                    ReportPropertyChanging("Registros");
                    _Registros = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Registros");
                    OnRegistrosChanged();
                }
            }
        }
        private global::System.Int32 _Registros;
        partial void OnRegistrosChanging(global::System.Int32 value);
        partial void OnRegistrosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ciclo
        {
            get
            {
                return _Ciclo;
            }
            set
            {
                if (_Ciclo != value)
                {
                    OnCicloChanging(value);
                    ReportPropertyChanging("Ciclo");
                    _Ciclo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ciclo");
                    OnCicloChanged();
                }
            }
        }
        private global::System.String _Ciclo;
        partial void OnCicloChanging(global::System.String value);
        partial void OnCicloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Duracion
        {
            get
            {
                return _Duracion;
            }
            set
            {
                OnDuracionChanging(value);
                ReportPropertyChanging("Duracion");
                _Duracion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duracion");
                OnDuracionChanged();
            }
        }
        private Nullable<global::System.Double> _Duracion;
        partial void OnDuracionChanging(Nullable<global::System.Double> value);
        partial void OnDuracionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> DBFs
        {
            get
            {
                return _DBFs;
            }
            set
            {
                OnDBFsChanging(value);
                ReportPropertyChanging("DBFs");
                _DBFs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DBFs");
                OnDBFsChanged();
            }
        }
        private Nullable<global::System.SByte> _DBFs;
        partial void OnDBFsChanging(Nullable<global::System.SByte> value);
        partial void OnDBFsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fua
        {
            get
            {
                return _fua;
            }
            set
            {
                OnfuaChanging(value);
                ReportPropertyChanging("fua");
                _fua = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fua");
                OnfuaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fua;
        partial void OnfuaChanging(Nullable<global::System.DateTime> value);
        partial void OnfuaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                if (_Fecha != value)
                {
                    OnFechaChanging(value);
                    ReportPropertyChanging("Fecha");
                    _Fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Fecha");
                    OnFechaChanged();
                }
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EscolarModel", Name="vwPlantele")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwPlantele : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwPlantele object.
        /// </summary>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static vwPlantele CreatevwPlantele(global::System.Byte activo)
        {
            vwPlantele vwPlantele = new vwPlantele();
            vwPlantele.Activo = activo;
            return vwPlantele;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idZona
        {
            get
            {
                return _idZona;
            }
            set
            {
                OnidZonaChanging(value);
                ReportPropertyChanging("idZona");
                _idZona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idZona");
                OnidZonaChanged();
            }
        }
        private Nullable<global::System.Int32> _idZona;
        partial void OnidZonaChanging(Nullable<global::System.Int32> value);
        partial void OnidZonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idPlantel
        {
            get
            {
                return _idPlantel;
            }
            set
            {
                OnidPlantelChanging(value);
                ReportPropertyChanging("idPlantel");
                _idPlantel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPlantel");
                OnidPlantelChanged();
            }
        }
        private Nullable<global::System.Int32> _idPlantel;
        partial void OnidPlantelChanging(Nullable<global::System.Int32> value);
        partial void OnidPlantelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> EsEmsad
        {
            get
            {
                return _EsEmsad;
            }
            set
            {
                OnEsEmsadChanging(value);
                ReportPropertyChanging("EsEmsad");
                _EsEmsad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsEmsad");
                OnEsEmsadChanged();
            }
        }
        private Nullable<global::System.SByte> _EsEmsad;
        partial void OnEsEmsadChanging(Nullable<global::System.SByte> value);
        partial void OnEsEmsadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IdMunicipio
        {
            get
            {
                return _IdMunicipio;
            }
            set
            {
                OnIdMunicipioChanging(value);
                ReportPropertyChanging("IdMunicipio");
                _IdMunicipio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdMunicipio");
                OnIdMunicipioChanged();
            }
        }
        private Nullable<global::System.Byte> _IdMunicipio;
        partial void OnIdMunicipioChanging(Nullable<global::System.Byte> value);
        partial void OnIdMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                if (_Activo != value)
                {
                    OnActivoChanging(value);
                    ReportPropertyChanging("Activo");
                    _Activo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Activo");
                    OnActivoChanged();
                }
            }
        }
        private global::System.Byte _Activo;
        partial void OnActivoChanging(global::System.Byte value);
        partial void OnActivoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EscolarModel", Name="vwRPTParcial1XALU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwRPTParcial1XALU : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwRPTParcial1XALU object.
        /// </summary>
        /// <param name="or_zona">Initial value of the or_zona property.</param>
        /// <param name="or_plant">Initial value of the or_plant property.</param>
        /// <param name="or_turno">Initial value of the or_turno property.</param>
        /// <param name="or_semest">Initial value of the or_semest property.</param>
        /// <param name="or_grupo">Initial value of the or_grupo property.</param>
        /// <param name="or_matric">Initial value of the or_matric property.</param>
        /// <param name="ciclo">Initial value of the Ciclo property.</param>
        /// <param name="periodo">Initial value of the Periodo property.</param>
        /// <param name="materias">Initial value of the Materias property.</param>
        /// <param name="reprobadasP1">Initial value of the ReprobadasP1 property.</param>
        /// <param name="promedioP1">Initial value of the PromedioP1 property.</param>
        /// <param name="observaciones">Initial value of the Observaciones property.</param>
        /// <param name="nombreAlumno">Initial value of the NombreAlumno property.</param>
        /// <param name="nombrePlantel">Initial value of the NombrePlantel property.</param>
        /// <param name="porcentaje">Initial value of the Porcentaje property.</param>
        public static vwRPTParcial1XALU CreatevwRPTParcial1XALU(global::System.Byte or_zona, global::System.Byte or_plant, global::System.Byte or_turno, global::System.Byte or_semest, global::System.Int32 or_grupo, global::System.String or_matric, global::System.String ciclo, global::System.Byte periodo, global::System.Byte materias, global::System.Byte reprobadasP1, global::System.Decimal promedioP1, global::System.String observaciones, global::System.String nombreAlumno, global::System.String nombrePlantel, global::System.Decimal porcentaje)
        {
            vwRPTParcial1XALU vwRPTParcial1XALU = new vwRPTParcial1XALU();
            vwRPTParcial1XALU.or_zona = or_zona;
            vwRPTParcial1XALU.or_plant = or_plant;
            vwRPTParcial1XALU.or_turno = or_turno;
            vwRPTParcial1XALU.or_semest = or_semest;
            vwRPTParcial1XALU.or_grupo = or_grupo;
            vwRPTParcial1XALU.or_matric = or_matric;
            vwRPTParcial1XALU.Ciclo = ciclo;
            vwRPTParcial1XALU.Periodo = periodo;
            vwRPTParcial1XALU.Materias = materias;
            vwRPTParcial1XALU.ReprobadasP1 = reprobadasP1;
            vwRPTParcial1XALU.PromedioP1 = promedioP1;
            vwRPTParcial1XALU.Observaciones = observaciones;
            vwRPTParcial1XALU.NombreAlumno = nombreAlumno;
            vwRPTParcial1XALU.NombrePlantel = nombrePlantel;
            vwRPTParcial1XALU.Porcentaje = porcentaje;
            return vwRPTParcial1XALU;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte or_zona
        {
            get
            {
                return _or_zona;
            }
            set
            {
                if (_or_zona != value)
                {
                    Onor_zonaChanging(value);
                    ReportPropertyChanging("or_zona");
                    _or_zona = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_zona");
                    Onor_zonaChanged();
                }
            }
        }
        private global::System.Byte _or_zona;
        partial void Onor_zonaChanging(global::System.Byte value);
        partial void Onor_zonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte or_plant
        {
            get
            {
                return _or_plant;
            }
            set
            {
                if (_or_plant != value)
                {
                    Onor_plantChanging(value);
                    ReportPropertyChanging("or_plant");
                    _or_plant = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_plant");
                    Onor_plantChanged();
                }
            }
        }
        private global::System.Byte _or_plant;
        partial void Onor_plantChanging(global::System.Byte value);
        partial void Onor_plantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte or_turno
        {
            get
            {
                return _or_turno;
            }
            set
            {
                if (_or_turno != value)
                {
                    Onor_turnoChanging(value);
                    ReportPropertyChanging("or_turno");
                    _or_turno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_turno");
                    Onor_turnoChanged();
                }
            }
        }
        private global::System.Byte _or_turno;
        partial void Onor_turnoChanging(global::System.Byte value);
        partial void Onor_turnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte or_semest
        {
            get
            {
                return _or_semest;
            }
            set
            {
                if (_or_semest != value)
                {
                    Onor_semestChanging(value);
                    ReportPropertyChanging("or_semest");
                    _or_semest = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_semest");
                    Onor_semestChanged();
                }
            }
        }
        private global::System.Byte _or_semest;
        partial void Onor_semestChanging(global::System.Byte value);
        partial void Onor_semestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 or_grupo
        {
            get
            {
                return _or_grupo;
            }
            set
            {
                if (_or_grupo != value)
                {
                    Onor_grupoChanging(value);
                    ReportPropertyChanging("or_grupo");
                    _or_grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_grupo");
                    Onor_grupoChanged();
                }
            }
        }
        private global::System.Int32 _or_grupo;
        partial void Onor_grupoChanging(global::System.Int32 value);
        partial void Onor_grupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String or_matric
        {
            get
            {
                return _or_matric;
            }
            set
            {
                if (_or_matric != value)
                {
                    Onor_matricChanging(value);
                    ReportPropertyChanging("or_matric");
                    _or_matric = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("or_matric");
                    Onor_matricChanged();
                }
            }
        }
        private global::System.String _or_matric;
        partial void Onor_matricChanging(global::System.String value);
        partial void Onor_matricChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ciclo
        {
            get
            {
                return _Ciclo;
            }
            set
            {
                if (_Ciclo != value)
                {
                    OnCicloChanging(value);
                    ReportPropertyChanging("Ciclo");
                    _Ciclo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ciclo");
                    OnCicloChanged();
                }
            }
        }
        private global::System.String _Ciclo;
        partial void OnCicloChanging(global::System.String value);
        partial void OnCicloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Periodo
        {
            get
            {
                return _Periodo;
            }
            set
            {
                if (_Periodo != value)
                {
                    OnPeriodoChanging(value);
                    ReportPropertyChanging("Periodo");
                    _Periodo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Periodo");
                    OnPeriodoChanged();
                }
            }
        }
        private global::System.Byte _Periodo;
        partial void OnPeriodoChanging(global::System.Byte value);
        partial void OnPeriodoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Materias
        {
            get
            {
                return _Materias;
            }
            set
            {
                OnMateriasChanging(value);
                ReportPropertyChanging("Materias");
                _Materias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Materias");
                OnMateriasChanged();
            }
        }
        private global::System.Byte _Materias;
        partial void OnMateriasChanging(global::System.Byte value);
        partial void OnMateriasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ReprobadasP1
        {
            get
            {
                return _ReprobadasP1;
            }
            set
            {
                OnReprobadasP1Changing(value);
                ReportPropertyChanging("ReprobadasP1");
                _ReprobadasP1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReprobadasP1");
                OnReprobadasP1Changed();
            }
        }
        private global::System.Byte _ReprobadasP1;
        partial void OnReprobadasP1Changing(global::System.Byte value);
        partial void OnReprobadasP1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PromedioP1
        {
            get
            {
                return _PromedioP1;
            }
            set
            {
                OnPromedioP1Changing(value);
                ReportPropertyChanging("PromedioP1");
                _PromedioP1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromedioP1");
                OnPromedioP1Changed();
            }
        }
        private global::System.Decimal _PromedioP1;
        partial void OnPromedioP1Changing(global::System.Decimal value);
        partial void OnPromedioP1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Observaciones
        {
            get
            {
                return _Observaciones;
            }
            set
            {
                OnObservacionesChanging(value);
                ReportPropertyChanging("Observaciones");
                _Observaciones = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Observaciones");
                OnObservacionesChanged();
            }
        }
        private global::System.String _Observaciones;
        partial void OnObservacionesChanging(global::System.String value);
        partial void OnObservacionesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreAlumno
        {
            get
            {
                return _NombreAlumno;
            }
            set
            {
                OnNombreAlumnoChanging(value);
                ReportPropertyChanging("NombreAlumno");
                _NombreAlumno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreAlumno");
                OnNombreAlumnoChanged();
            }
        }
        private global::System.String _NombreAlumno;
        partial void OnNombreAlumnoChanging(global::System.String value);
        partial void OnNombreAlumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombrePlantel
        {
            get
            {
                return _NombrePlantel;
            }
            set
            {
                OnNombrePlantelChanging(value);
                ReportPropertyChanging("NombrePlantel");
                _NombrePlantel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombrePlantel");
                OnNombrePlantelChanged();
            }
        }
        private global::System.String _NombrePlantel;
        partial void OnNombrePlantelChanging(global::System.String value);
        partial void OnNombrePlantelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Porcentaje
        {
            get
            {
                return _Porcentaje;
            }
            set
            {
                OnPorcentajeChanging(value);
                ReportPropertyChanging("Porcentaje");
                _Porcentaje = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Porcentaje");
                OnPorcentajeChanged();
            }
        }
        private global::System.Decimal _Porcentaje;
        partial void OnPorcentajeChanging(global::System.Decimal value);
        partial void OnPorcentajeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EscolarModel", Name="vwRPTParcial1XGPO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwRPTParcial1XGPO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwRPTParcial1XGPO object.
        /// </summary>
        /// <param name="or_zona">Initial value of the or_zona property.</param>
        /// <param name="or_plant">Initial value of the or_plant property.</param>
        /// <param name="or_turno">Initial value of the or_turno property.</param>
        /// <param name="or_semest">Initial value of the or_semest property.</param>
        /// <param name="or_grupo">Initial value of the or_grupo property.</param>
        /// <param name="or_asigna">Initial value of the or_asigna property.</param>
        /// <param name="or_maest">Initial value of the or_maest property.</param>
        /// <param name="ciclo">Initial value of the Ciclo property.</param>
        /// <param name="periodo">Initial value of the Periodo property.</param>
        /// <param name="alumnos">Initial value of the Alumnos property.</param>
        /// <param name="clases">Initial value of the Clases property.</param>
        /// <param name="promAsist">Initial value of the PromAsist property.</param>
        /// <param name="promAsig">Initial value of the PromAsig property.</param>
        /// <param name="reprobados">Initial value of the Reprobados property.</param>
        /// <param name="nombreAsig">Initial value of the NombreAsig property.</param>
        /// <param name="nombreMaest">Initial value of the NombreMaest property.</param>
        /// <param name="nombrePlantel">Initial value of the NombrePlantel property.</param>
        /// <param name="porcentaje">Initial value of the Porcentaje property.</param>
        public static vwRPTParcial1XGPO CreatevwRPTParcial1XGPO(global::System.Byte or_zona, global::System.Int32 or_plant, global::System.Byte or_turno, global::System.Byte or_semest, global::System.Int32 or_grupo, global::System.Int32 or_asigna, global::System.Int64 or_maest, global::System.String ciclo, global::System.Byte periodo, global::System.Int64 alumnos, global::System.Byte clases, global::System.Decimal promAsist, global::System.Decimal promAsig, global::System.Int64 reprobados, global::System.String nombreAsig, global::System.String nombreMaest, global::System.String nombrePlantel, global::System.Decimal porcentaje)
        {
            vwRPTParcial1XGPO vwRPTParcial1XGPO = new vwRPTParcial1XGPO();
            vwRPTParcial1XGPO.or_zona = or_zona;
            vwRPTParcial1XGPO.or_plant = or_plant;
            vwRPTParcial1XGPO.or_turno = or_turno;
            vwRPTParcial1XGPO.or_semest = or_semest;
            vwRPTParcial1XGPO.or_grupo = or_grupo;
            vwRPTParcial1XGPO.or_asigna = or_asigna;
            vwRPTParcial1XGPO.or_maest = or_maest;
            vwRPTParcial1XGPO.Ciclo = ciclo;
            vwRPTParcial1XGPO.Periodo = periodo;
            vwRPTParcial1XGPO.Alumnos = alumnos;
            vwRPTParcial1XGPO.Clases = clases;
            vwRPTParcial1XGPO.PromAsist = promAsist;
            vwRPTParcial1XGPO.PromAsig = promAsig;
            vwRPTParcial1XGPO.Reprobados = reprobados;
            vwRPTParcial1XGPO.NombreAsig = nombreAsig;
            vwRPTParcial1XGPO.NombreMaest = nombreMaest;
            vwRPTParcial1XGPO.NombrePlantel = nombrePlantel;
            vwRPTParcial1XGPO.Porcentaje = porcentaje;
            return vwRPTParcial1XGPO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte or_zona
        {
            get
            {
                return _or_zona;
            }
            set
            {
                if (_or_zona != value)
                {
                    Onor_zonaChanging(value);
                    ReportPropertyChanging("or_zona");
                    _or_zona = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_zona");
                    Onor_zonaChanged();
                }
            }
        }
        private global::System.Byte _or_zona;
        partial void Onor_zonaChanging(global::System.Byte value);
        partial void Onor_zonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 or_plant
        {
            get
            {
                return _or_plant;
            }
            set
            {
                if (_or_plant != value)
                {
                    Onor_plantChanging(value);
                    ReportPropertyChanging("or_plant");
                    _or_plant = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_plant");
                    Onor_plantChanged();
                }
            }
        }
        private global::System.Int32 _or_plant;
        partial void Onor_plantChanging(global::System.Int32 value);
        partial void Onor_plantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte or_turno
        {
            get
            {
                return _or_turno;
            }
            set
            {
                if (_or_turno != value)
                {
                    Onor_turnoChanging(value);
                    ReportPropertyChanging("or_turno");
                    _or_turno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_turno");
                    Onor_turnoChanged();
                }
            }
        }
        private global::System.Byte _or_turno;
        partial void Onor_turnoChanging(global::System.Byte value);
        partial void Onor_turnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte or_semest
        {
            get
            {
                return _or_semest;
            }
            set
            {
                if (_or_semest != value)
                {
                    Onor_semestChanging(value);
                    ReportPropertyChanging("or_semest");
                    _or_semest = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_semest");
                    Onor_semestChanged();
                }
            }
        }
        private global::System.Byte _or_semest;
        partial void Onor_semestChanging(global::System.Byte value);
        partial void Onor_semestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 or_grupo
        {
            get
            {
                return _or_grupo;
            }
            set
            {
                if (_or_grupo != value)
                {
                    Onor_grupoChanging(value);
                    ReportPropertyChanging("or_grupo");
                    _or_grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_grupo");
                    Onor_grupoChanged();
                }
            }
        }
        private global::System.Int32 _or_grupo;
        partial void Onor_grupoChanging(global::System.Int32 value);
        partial void Onor_grupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 or_asigna
        {
            get
            {
                return _or_asigna;
            }
            set
            {
                if (_or_asigna != value)
                {
                    Onor_asignaChanging(value);
                    ReportPropertyChanging("or_asigna");
                    _or_asigna = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_asigna");
                    Onor_asignaChanged();
                }
            }
        }
        private global::System.Int32 _or_asigna;
        partial void Onor_asignaChanging(global::System.Int32 value);
        partial void Onor_asignaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 or_maest
        {
            get
            {
                return _or_maest;
            }
            set
            {
                if (_or_maest != value)
                {
                    Onor_maestChanging(value);
                    ReportPropertyChanging("or_maest");
                    _or_maest = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("or_maest");
                    Onor_maestChanged();
                }
            }
        }
        private global::System.Int64 _or_maest;
        partial void Onor_maestChanging(global::System.Int64 value);
        partial void Onor_maestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ciclo
        {
            get
            {
                return _Ciclo;
            }
            set
            {
                if (_Ciclo != value)
                {
                    OnCicloChanging(value);
                    ReportPropertyChanging("Ciclo");
                    _Ciclo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ciclo");
                    OnCicloChanged();
                }
            }
        }
        private global::System.String _Ciclo;
        partial void OnCicloChanging(global::System.String value);
        partial void OnCicloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Periodo
        {
            get
            {
                return _Periodo;
            }
            set
            {
                if (_Periodo != value)
                {
                    OnPeriodoChanging(value);
                    ReportPropertyChanging("Periodo");
                    _Periodo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Periodo");
                    OnPeriodoChanged();
                }
            }
        }
        private global::System.Byte _Periodo;
        partial void OnPeriodoChanging(global::System.Byte value);
        partial void OnPeriodoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Alumnos
        {
            get
            {
                return _Alumnos;
            }
            set
            {
                OnAlumnosChanging(value);
                ReportPropertyChanging("Alumnos");
                _Alumnos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Alumnos");
                OnAlumnosChanged();
            }
        }
        private global::System.Int64 _Alumnos;
        partial void OnAlumnosChanging(global::System.Int64 value);
        partial void OnAlumnosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Clases
        {
            get
            {
                return _Clases;
            }
            set
            {
                OnClasesChanging(value);
                ReportPropertyChanging("Clases");
                _Clases = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Clases");
                OnClasesChanged();
            }
        }
        private global::System.Byte _Clases;
        partial void OnClasesChanging(global::System.Byte value);
        partial void OnClasesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PromAsist
        {
            get
            {
                return _PromAsist;
            }
            set
            {
                OnPromAsistChanging(value);
                ReportPropertyChanging("PromAsist");
                _PromAsist = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromAsist");
                OnPromAsistChanged();
            }
        }
        private global::System.Decimal _PromAsist;
        partial void OnPromAsistChanging(global::System.Decimal value);
        partial void OnPromAsistChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PromAsig
        {
            get
            {
                return _PromAsig;
            }
            set
            {
                OnPromAsigChanging(value);
                ReportPropertyChanging("PromAsig");
                _PromAsig = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromAsig");
                OnPromAsigChanged();
            }
        }
        private global::System.Decimal _PromAsig;
        partial void OnPromAsigChanging(global::System.Decimal value);
        partial void OnPromAsigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Reprobados
        {
            get
            {
                return _Reprobados;
            }
            set
            {
                OnReprobadosChanging(value);
                ReportPropertyChanging("Reprobados");
                _Reprobados = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reprobados");
                OnReprobadosChanged();
            }
        }
        private global::System.Int64 _Reprobados;
        partial void OnReprobadosChanging(global::System.Int64 value);
        partial void OnReprobadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreAsig
        {
            get
            {
                return _NombreAsig;
            }
            set
            {
                OnNombreAsigChanging(value);
                ReportPropertyChanging("NombreAsig");
                _NombreAsig = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreAsig");
                OnNombreAsigChanged();
            }
        }
        private global::System.String _NombreAsig;
        partial void OnNombreAsigChanging(global::System.String value);
        partial void OnNombreAsigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreMaest
        {
            get
            {
                return _NombreMaest;
            }
            set
            {
                OnNombreMaestChanging(value);
                ReportPropertyChanging("NombreMaest");
                _NombreMaest = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreMaest");
                OnNombreMaestChanged();
            }
        }
        private global::System.String _NombreMaest;
        partial void OnNombreMaestChanging(global::System.String value);
        partial void OnNombreMaestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombrePlantel
        {
            get
            {
                return _NombrePlantel;
            }
            set
            {
                OnNombrePlantelChanging(value);
                ReportPropertyChanging("NombrePlantel");
                _NombrePlantel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombrePlantel");
                OnNombrePlantelChanged();
            }
        }
        private global::System.String _NombrePlantel;
        partial void OnNombrePlantelChanging(global::System.String value);
        partial void OnNombrePlantelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Porcentaje
        {
            get
            {
                return _Porcentaje;
            }
            set
            {
                OnPorcentajeChanging(value);
                ReportPropertyChanging("Porcentaje");
                _Porcentaje = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Porcentaje");
                OnPorcentajeChanged();
            }
        }
        private global::System.Decimal _Porcentaje;
        partial void OnPorcentajeChanging(global::System.Decimal value);
        partial void OnPorcentajeChanged();

        #endregion

    
    }

    #endregion

    
}
